### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by FleischerT** [pichlerpa/PowerBITrinoConnector#1]
Hello pichlerpa,

first of all thank you very much for your work!

I came across your connector after a web search on how to connect Power BI with Trino. Two questions came to my mind, first is it possible that you add a license? And second, are you actively developing the connector so that future changes to the Rest API will also be supported by the connector?

**Comment by pichlerpa** [comment]
Hi @FleischerT.

No, the connector isn't currently in active development but changes to the REST API happen quite rare I would say and anybody could contribute as well. Do you have any specific feature in mind?

As to licensing, I suppose you refer to [certify](https://docs.microsoft.com/en-us/power-query/connectorcertification) the connector to also be available in the Power BI Service without using an on-prem. gateway? Yes, this could be done but requires some prerequisites which are difficult for me to meet alone, especially because I am not really part of the Starburst/Trino team and hence have no connection to any customers. However, it's still on my list to contribute this to the Trino community and make it part of the official repo, this should help the connector to grow and maybe one day be certified by Microsoft as well.

Patrick

**Comment by FleischerT** [comment]
Hi @pichlerpa ,

Sorry for the ambiguity, by license I meant a license to use your code. 
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by pichlerpa** [comment]
@FleischerT done, but I have planned to make this part of the official Trino repo anwyay, just haven't had time so far.
